### ISSUE TITLE
数据库具体是哪种？

### ISSUE THREAD

**Issue by rs-v** [A-islander/islander-forum-system#1]

**Comment by rs-v** [comment]
mysql吗？

**Comment by A-islander** [comment]
是的，可以在config/config.go中查看，使用的是msql
________________________________
发件人: Animoe ***@***.***>
发送时间: 2022年5月10日 9:47
收件人: A-islander/islander-forum-system ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [A-islander/islander-forum-system] 数据库具体是哪种？ (Issue #1)


Closed #1<https://github.com/A-islander/islander-forum-system/issues/1>.

―

**Comment by A-islander** [comment]
或者在model/commonModel.go中可以看见使用的是mysql驱动
________________________________
发件人: Animoe ***@***.***>
发送时间: 2022年5月10日 9:47
收件人: A-islander/islander-forum-system ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [A-islander/islander-forum-system] 数据库具体是哪种？ (Issue #1)


Closed #1<https://github.com/A-islander/islander-forum-system/issues/1>.

―
