### ISSUE TITLE
config.json 里各变量可以详细解释一下吗？

### ISSUE THREAD

**Issue by rs-v** [A-islander/islander-forum-system#2]

**Comment by rs-v** [comment]
比如说是否可以为空。default值是多少？

**Comment by A-islander** [comment]
当前输入字符串不能为空，为空的话会回调code403表示访问限制，默认值的话没设，可以自行设定，后续我想更改为发图的话就可以 不发字符串输入了
________________________________
发件人: Animoe ***@***.***>
发送时间: 2022年5月21日 21:58
收件人: A-islander/islander-forum-system ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [A-islander/islander-forum-system] config.json 里各变量可以详细解释一下吗？ (Issue #2)


比如说是否可以为空。default值是多少？

―

**Comment by A-islander** [comment]
啊，理解意思错误了，我config.json里的变量主要就是数据库，redis缓存层，图床还有rpc的配置参数
"userName": "", "passWord": "","ip": "","database": "",这几个为数据库的用户名和访问的ip
"sageNum": 20, 这里是有关sage设置，sage差值超过设定值将会sage
"rpcIp": "",这个是配合用户rpc远程调用使用的，就是islander_user_system运行的ip地址
"redisIp": "","buffTime": 0,这里是redis缓存层的配置，分别是redis的ip地址和缓存刷新时间
"imgUserName": "","imgPassWord": ""这里是我使用的图床的用户名和密码

在上面的设置中，最主要的是数据库的配置和rpc的配置，这两个必须填上，至于redis的配置，如果不配置redis，可以修改forumController.go中的model层函数，改为不使用缓存版
图床由于是非必须项也可以为空
________________________________
发件人: Animoe ***@***.***>
发送时间: 2022年5月21日 21:58
收件人: A-islander/islander-forum-system ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [A-islander/islander-forum-system] config.json 里各变量可以详细解释一下吗？ (Issue #2)


比如说是否可以为空。default值是多少？

―

**Comment by rs-v** [comment]
多谢解答😁
