### ISSUE TITLE
一些问题。

### ISSUE THREAD

**Issue by rs-v** [A-islander/islander-forum-system#3]
数据库初始化方法？
创建板块的api?

**Comment by rs-v** [comment]
我查看了route
`forumServer.Handle("/plate/get", mid(getForumPlate))
	forumServer.Handle("/forum/get", mid(getForumPost))
	forumServer.Handle("/forum/index", mid(getForumPostIndex))
	forumServer.Handle("/forum/list", mid(getForumPostList))
	forumServer.Handle("/forum/indexLast", mid(getForumIndexLastTime))
	forumServer.Handle("/forum/userList", mid(getUserForumPostList))
	forumServer.Handle("/forum/post", mid(postForumPost))
	forumServer.Handle("/forum/reply", mid(replyForumPost))
	forumServer.Handle("/forum/sage/add", mid(sageAdd))
	forumServer.Handle("/forum/sage/sub", mid(sageSub))
	forumServer.Handle("/forum/sage/list", mid(sageList))
	forumServer.Handle("/img/token", mid(getImgToken))
	forumServer.Handle("/img/upload", mid(postImgUpload))`
似乎不存在创建板块的方法，是手动创建吗？那么有无可导入的sql方法？

**Comment by A-islander** [comment]
我傻了，忘记把数据库结构给放出来了，我等下把初始化sql放出来
________________________________
发件人: Animoe ***@***.***>
发送时间: 2022年5月21日 23:10
收件人: A-islander/islander-forum-system ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [A-islander/islander-forum-system] 一些问题。 (Issue #3)


我查看了route
forumServer.Handle("/plate/get", mid(getForumPlate)) forumServer.Handle("/forum/get", mid(getForumPost)) forumServer.Handle("/forum/index", mid(getForumPostIndex)) forumServer.Handle("/forum/list", mid(getForumPostList)) forumServer.Handle("/forum/indexLast", mid(getForumIndexLastTime)) forumServer.Handle("/forum/userList", mid(getUserForumPostList)) forumServer.Handle("/forum/post", mid(postForumPost)) forumServer.Handle("/forum/reply", mid(replyForumPost)) forumServer.Handle("/forum/sage/add", mid(sageAdd)) forumServer.Handle("/forum/sage/sub", mid(sageSub)) forumServer.Handle("/forum/sage/list", mid(sageList)) forumServer.Handle("/img/token", mid(getImgToken)) forumServer.Handle("/img/upload", mid(postImgUpload))
似乎不存在创建板块的方法，是手动创建吗？那么有无可导入的sql方法？

―

**Comment by rs-v** [comment]
多谢
